### ISSUE TITLE
Titra seems not to be running within a Docker Swarm

### ISSUE THREAD

**Issue by NK0D1NG** [kromitgmbh/titra#106]
Hello,
I wanted to try out Titra, but I have problems get it up and running within my Docker Swarm Cluster.
I am using Traefik v2 as a reverse proxy. I get redirected to the signin page, but the page is empty or is not looking correctly:
![grafik](https://user-images.githubusercontent.com/88783636/157710749-8f02b594-01a6-458d-a885-9300e3c40f77.png)

I think there is a problem loading the css/js files? Should I use localhost as the ROOT_URL? The deployment instructions are not that precise..

```

titra_app.1.yfsdkt8qf9cc@v220210169548138574    | [ERROR: [ostrio:flow-router-extra] [route.wait] Promise not resolved @ Thu Mar 10 2022 16:30:45 GMT+0000 (Coordinated Universal Time)] {
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |   "browserInfo": {
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |     "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0",
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |     "userId": null,
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |     "url": "https://titra.mydomain.de/",
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |     "resolution": "3440x1440"
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |   },
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |   "stack": {}
titra_app.1.yfsdkt8qf9cc@v220210169548138574    | }
titra_app.1.yfsdkt8qf9cc@v220210169548138574    | [ERROR: TypeError: $(...).popover is not a function @ Thu Mar 10 2022 16:30:45 GMT+0000 (Coordinated Universal Time)] {
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |   "file": "https://titra.mydomain.de/7db791e51d98db0c3681323b36f53d484eb0660a.js?meteor_js_resource=true",
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |   "onLine": 206,
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |   "browserInfo": {
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |     "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0",
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |     "userId": null,
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |     "url": "https://titra.mydomain.de/signIn",
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |     "resolution": "3440x1440"
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |   }
titra_app.1.yfsdkt8qf9cc@v220210169548138574    | }

```

The database service is running and the logs don't show anything error related.

This is my Docker-Compose File:
```
version: "3.5"
services:
  app:
    image: kromit/titra
    environment:
      - ROOT_URL=https://titra.mydomain.de?directConnect=true
      - MONGO_URL=mongodb://mongodb/titra?directConnection=true
      - PORT=3000
    networks:
      - titra
      - traefik-public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - traefik.http.routers.titra-http.rule=Host(`titra.mydomain.de`)
        - traefik.http.routers.titra-http.entrypoints=http
        - traefik.http.routers.titra-http.middlewares=https-redirect
        - "traefik.http.routers.titra-https.rule=Host(`titra.mydomain.de`)"
        - "traefik.http.routers.titra-https.tls=true"
        - "traefik.http.routers.titra-https.tls.certresolver=netcup"
        - "traefik.http.routers.titra-https.entrypoints=https"
        - "traefik.http.services.titra.loadbalancer.server.port=3000"
    ports:
      - 4000:3000

  mongodb:
    image: mongo:4.4
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=false
    volumes:
      - titra:/data/db
    networks:
      - titra

volumes:
  titra:
    driver_opts:
      type: "nfs"
      o: "addr=mynfs,nolock,soft,rw"
      device: ":/srv/storage/titra"

networks:
  traefik-public:
    external: true
  titra:
    driver: overlay
```
Any hints what the problem could be?

**Comment by faburem** [comment]
Hi,
this is actually a pretty nice coincidence because I was working on some improvements of the docker (compose) files this week. I have corrected a mistake that you have copied over from the docker-compose.yml example file in the repo.
      - ROOT_URL=https://titra.mydomain.de?directConnect=true
The ROOT_URL should be the URL under which titra is served, however the ?directConnect=true parameter should not be there, it is only relevant for the MONGO_URL. So to stick with your example it should be:
      - ROOT_URL=https://titra.mydomain.de
Despite this I have just released the improvements to the titra docker container which now waits for the MongoDB to boot up before starting titra. I know this was causing issues in the past for the first launch of titra and it might also help with your docker swarm use case! Please give it a try with titra version 0.71.0 and let me know if it works for you.

Also, I was able to shave another 50MB off the uncompressed titra Docker image 💪

Best,
Fabian

**Comment by NKnuelle** [comment]
Hi @faburem 
it's working now. I still have some small issues: Everytime I login with another user the stylesheet is messed up:
![grafik](https://user-images.githubusercontent.com/24235417/158261791-492701a2-e7e0-4bc2-9c14-736759830303.png)

If I reload the page (F5 is enough, without cache clearing) the stylesheet is fine and the page has a dark theme:
![grafik](https://user-images.githubusercontent.com/24235417/158261909-07acc23c-350c-44d4-a985-e041626b6713.png)

Also a few questions about a production setup:
- How to configure the SMTP server?
- How to disable the registration of new users? / How can I create new users without registration?

I will look into the software. Looks promising to me. Thank you for your work!

Greetings

**Comment by faburem** [comment]
Hi,
thanks for the feedback. I am aware of this css glitch which happens if there is a discrepancy between the auto detected preferred color scheme during login (the user settings are not known at this time) and the use settings in titra. I will investigate possibilities to improve this, but luckily the fix is easy enough by refreshing the page.

- For the configuration of the SMTP server you can find the information in our wiki https://wiki.titra.io/books/deployment/page/environment-variables.
- New user registration can be disabled under administration / global settings:
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/11456790/158816894-d5edebbb-952d-428e-8ff4-373eeaeec455.png">

There is a lot to explore in the wiki and in the settings I hope you like it!

Best,
Fabian

**Comment by faburem** [comment]
Closing this issue due to inactivity.
